name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Environment
        run: |
          # Replace placeholder values with actual secrets
          sed -i "s/__EMAILJS_PUBLIC_KEY__/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" index.html
          
          # Create the config file with EmailJS settings
          echo "const EMAILJS_CONFIG = {
            SERVICE_ID: '${{ secrets.EMAILJS_SERVICE_ID }}',
            TEMPLATE_ID: '${{ secrets.EMAILJS_TEMPLATE_ID }}'
          };" > emailjs-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .         # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
          clean: true      # Automatically remove deleted files from the deployment 