name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Environment
        run: |
          # Replace placeholder values with actual secrets
          sed -i "s/__EMAILJS_PUBLIC_KEY__/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" index.html
          
          # Create the config file with EmailJS settings
          echo "const EMAILJS_CONFIG = {
            SERVICE_ID: '${{ secrets.EMAILJS_SERVICE_ID }}',
            TEMPLATE_ID: '${{ secrets.EMAILJS_TEMPLATE_ID }}'
          };" > emailjs-config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: .         # The folder the action should deploy
          clean: true       # Automatically remove deleted files from the deployment 